config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  resources :tickets do
    resources :excavators
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'rgeo/geo_json'
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_many :excavators
	serialize :additional_service_area_codes, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all #Ticket.include(excavators).all
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @excavator = @ticket.excavators.new(excavator_params)
    respond_to do |format|
      if @ticket.save && @excavator.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:request_number, :sequence_number, :request_type, :request_taken, :transmission_date_time, :legal, :response_due, :restake_on, :expiration_on, :primary_service_area_code, :additional_service_area_codes, :digsiteInfo)
    end

      def excavator_params
      params.require(:excavator).permit(:ticket_id, :company_name, :address, :crew_on_site)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBJLgU2TedtXRi12-aM8iO2Ii59bOCzdU8&callback=initMap">
    
</script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table class="table-default">
  <thead>
    <tr>
      <th>Request number</th>
      <th>Sequence number</th>
      <th>Request type</th>
      <th>Request taken</th>
      <th>Transmission date time</th>
      <th>Legal</th>
      <th>Response due</th>
      <th>Restake on</th>
      <th>Expiration on</th>
      <th>Primary service area code</th>
      <th>Additional service area codes</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.request_number %></td>
        <td><%= ticket.sequence_number %></td>
        <td><%= ticket.request_type %></td>
        <td><%= ticket.request_taken %></td>
        <td><%= ticket.transmission_date_time %></td>
        <td><%= ticket.legal %></td>
        <td><%= ticket.response_due %></td>
        <td><%= ticket.restake_on %></td>
        <td><%= ticket.expiration_on %></td>
        <td><%= ticket.primary_service_area_code %></td>
        <td><%= ticket.additional_service_area_codes %></td>
        <td><%= link_to 'Show', ticket_path(ticket) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Request number:</strong>
  <%= @ticket.request_number %>
</p>

<p>
  <strong>Sequence number:</strong>
  <%= @ticket.sequence_number %>
</p>

<p>
  <strong>Request type:</strong>
  <%= @ticket.request_type %>
</p>

<p>
  <strong>Request taken:</strong>
  <%= @ticket.request_taken %>
</p>

<p>
  <strong>Transmission date time:</strong>
  <%= @ticket.transmission_date_time %>
</p>

<p>
  <strong>Legal:</strong>
  <%= @ticket.legal %>
</p>

<p>
  <strong>Response due:</strong>
  <%= @ticket.response_due %>
</p>

<p>
  <strong>Restake on:</strong>
  <%= @ticket.restake_on %>
</p>

<p>
  <strong>Expiration on:</strong>
  <%= @ticket.expiration_on %>
</p>

<p>
  <strong>Primary service area code:</strong>
  <%= @ticket.primary_service_area_code %>
</p>

<p>
  <strong>Additional service area codes:</strong>
  <%= @ticket.additional_service_area_codes %>
</p>


<%= link_to 'Back', tickets_path %>

</br>

<div id="map"></div>

<script type="text/javascript">
/* It needs to be baselined as per the requirement. Kept it as is since I have to deliver it on commited time */
  $(window).on("load", function(){
    // var $polygons = "<%= @ticket.digsiteInfo unless @ticket.digsiteInfo.nil? %>";
    // window.localStorage.setItem('polygons', $polygons);
  });
</script>